version: "3.9"
services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ctserver
    ports:
      - "5000:5000"
    depends_on:
      - "db"
    environment:
      - ASPNETCORE_URLS=http://*:5000
      - ASPNETCORE_ENVIRONMENT=Development
    # - DB_STRING=Host=host.docker.internal;Port=5055;Database=ct;Username=postgres;Password=example;Include Error Detail=true
      - DB_STRING=Host=db;Port=5432;Database=ct;Username=postgres;Password=example;Include Error Detail=true

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
    ports:
      - "54320:5432"
