version: "3.9"
services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ct-server
    ports:
      - "5000:5000"
    depends_on:
      - "db"
    environment:
      - ASPNETCORE_URLS=http://*:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__Console__FormatterName
      - DB_STRING=Host=db;Port=5432;Database=ct;Username=postgres;Password=example;Include Error Detail=true
    # - DB_STRING=Host=host.docker.internal;Port=5055;Database=ct;Username=postgres;Password=example;Include Error Detail=true
      - Jwt__Secret=placeholder - replace in prod#32
      - Storage__AttachmentsPath=attachments
      - Storage__PhotosPath=photos

      # https://console.firebase.google.com/
      - WebPush__IsEnabled=false
      - WebPush__ServerKey=
      - WebPush__SenderId=
      - WebPush__Subject=mailto:example@example.com
      - WebPush__PublicKey=
      - WebPush__PrivateKey=
    volumes:
      - ./data/attachments:/app/attachments

  db:
    image: postgres
    container_name: ct-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
    ports:
      - "54320:5432"
